name: dev
channels:
- conda-forge
dependencies:
- python=3.10
- numpy
- scipy
- pandas
- pytest
- pytest-cov
- hypothesis
- scikit-learn
- coverage
- codecov
- ninja
- lcov
- cmake
- llvm-openmp
- cython
- cpplint
- pylint
- awscli
- python-build
- pip
- pip:
  - cibuildwheel
  - xgboost
  - lightgbm
