/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ml_dmlc_treelite4j_java_TreeliteJNI */

#ifndef _Included_ml_dmlc_treelite4j_java_TreeliteJNI
#define _Included_ml_dmlc_treelite4j_java_TreeliteJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreeliteGetLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreeliteGetLastError
  (JNIEnv *, jclass);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreeliteAssembleSparseBatch
 * Signature: ([F[I[JJJ[J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreeliteAssembleSparseBatch
  (JNIEnv *, jclass, jfloatArray, jintArray, jlongArray, jlong, jlong, jlongArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreeliteDeleteSparseBatch
 * Signature: (J[F[I[J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreeliteDeleteSparseBatch
  (JNIEnv *, jclass, jlong, jfloatArray, jintArray, jlongArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreeliteAssembleDenseBatch
 * Signature: ([FFJJ[J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreeliteAssembleDenseBatch
  (JNIEnv *, jclass, jfloatArray, jfloat, jlong, jlong, jlongArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreeliteDeleteDenseBatch
 * Signature: (J[F)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreeliteDeleteDenseBatch
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreeliteBatchGetDimension
 * Signature: (JZ[J[J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreeliteBatchGetDimension
  (JNIEnv *, jclass, jlong, jboolean, jlongArray, jlongArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorLoad
 * Signature: (Ljava/lang/String;I[J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorLoad
  (JNIEnv *, jclass, jstring, jint, jlongArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorPredictBatch
 * Signature: (JJZZZ[F[J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorPredictBatch
  (JNIEnv *, jclass, jlong, jlong, jboolean, jboolean, jboolean, jfloatArray, jlongArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorPredictInst
 * Signature: (J[BZ[F[J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorPredictInst
  (JNIEnv *, jclass, jlong, jbyteArray, jboolean, jfloatArray, jlongArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorQueryResultSize
 * Signature: (JJZ[J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorQueryResultSize
  (JNIEnv *, jclass, jlong, jlong, jboolean, jlongArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorQueryResultSizeSingleInst
 * Signature: (J[J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorQueryResultSizeSingleInst
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorQueryNumOutputGroup
 * Signature: (J[J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorQueryNumOutputGroup
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorQueryNumFeature
 * Signature: (J[J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorQueryNumFeature
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorQueryPredTransform
 * Signature: (J[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorQueryPredTransform
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorQuerySigmoidAlpha
 * Signature: (J[F)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorQuerySigmoidAlpha
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorQueryGlobalBias
 * Signature: (J[F)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorQueryGlobalBias
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorFree
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorFree
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
