/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ml_dmlc_treelite4j_java_TreeliteJNI */

#ifndef _Included_ml_dmlc_treelite4j_java_TreeliteJNI
#define _Included_ml_dmlc_treelite4j_java_TreeliteJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreeliteGetLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreeliteGetLastError
  (JNIEnv *, jclass);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreeliteDMatrixCreateFromCSRWithFloat32In
 * Signature: ([F[I[JJJ[J)I
 */
JNIEXPORT jint JNICALL
Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreeliteDMatrixCreateFromCSRWithFloat32In
  (JNIEnv *, jclass, jfloatArray, jintArray, jlongArray, jlong, jlong, jlongArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreeliteDMatrixCreateFromCSRWithFloat64In
 * Signature: ([D[I[JJJ[J)I
 */
JNIEXPORT jint JNICALL
Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreeliteDMatrixCreateFromCSRWithFloat64In
  (JNIEnv *, jclass, jdoubleArray, jintArray, jlongArray, jlong, jlong, jlongArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreeliteDMatrixCreateFromMatWithFloat32In
 * Signature: ([FJJF[J)I
 */
JNIEXPORT jint JNICALL
Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreeliteDMatrixCreateFromMatWithFloat32In
  (JNIEnv *, jclass, jfloatArray, jlong, jlong, jfloat, jlongArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreeliteDMatrixCreateFromMatWithFloat64In
 * Signature: ([DJJD[J)I
 */
JNIEXPORT jint JNICALL
Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreeliteDMatrixCreateFromMatWithFloat64In
  (JNIEnv *, jclass, jdoubleArray, jlong, jlong, jdouble, jlongArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreeliteDMatrixGetDimension
 * Signature: (J[J[J[J)I
 */
JNIEXPORT jint JNICALL
Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreeliteDMatrixGetDimension
  (JNIEnv *, jclass, jlong, jlongArray, jlongArray, jlongArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreeliteDMatrixFree
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL
Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreeliteDMatrixFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorLoad
 * Signature: (Ljava/lang/String;I[J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorLoad
  (JNIEnv *, jclass, jstring, jint, jlongArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorPredictBatchWithFloat32Out
 * Signature: (JJZZ[F[J)I
 */
JNIEXPORT jint JNICALL
Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorPredictBatchWithFloat32Out
  (JNIEnv *, jclass, jlong, jlong, jboolean, jboolean, jfloatArray, jlongArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorPredictBatchWithFloat64Out
 * Signature: (JJZZ[D[J)I
 */
JNIEXPORT jint JNICALL
Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorPredictBatchWithFloat64Out
  (JNIEnv *, jclass, jlong, jlong, jboolean, jboolean, jdoubleArray, jlongArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorPredictBatchWithUInt32Out
 * Signature: (JJZZ[I[J)I
 */
JNIEXPORT jint JNICALL
Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorPredictBatchWithUInt32Out
  (JNIEnv *, jclass, jlong, jlong, jboolean, jboolean, jintArray, jlongArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorQueryResultSize
 * Signature: (JJ[J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorQueryResultSize
  (JNIEnv *, jclass, jlong, jlong, jlongArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorQueryNumClass
 * Signature: (J[J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorQueryNumClass
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorQueryNumFeature
 * Signature: (J[J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorQueryNumFeature
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorQueryPredTransform
 * Signature: (J[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorQueryPredTransform
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorQuerySigmoidAlpha
 * Signature: (J[F)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorQuerySigmoidAlpha
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorQueryGlobalBias
 * Signature: (J[F)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorQueryGlobalBias
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorQueryThresholdType
 * Signature: (J[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorQueryThresholdType
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorQueryLeafOutputType
 * Signature: (J[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorQueryLeafOutputType
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     ml_dmlc_treelite4j_java_TreeliteJNI
 * Method:    TreelitePredictorFree
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ml_dmlc_treelite4j_java_TreeliteJNI_TreelitePredictorFree
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
