name: formatting-check

on: [push, pull_request]

permissions:
  contents: read  # to fetch code (actions/checkout)

defaults:
  run:
    shell: bash -l {0}

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - uses: mamba-org/provision-with-micromamba@v14
      with:
        cache-downloads: true
        cache-env: true
        environment-name: dev
        environment-file: ops/conda_env/dev.yml
    - name: Display Conda env
      run: |
        conda info
        conda list
    - name: Run formatting check
      run: |
        bash ops/run-formatting-check.sh
