name: linux-wheel-builder

on:
  pull_request:
  push:
  schedule:
    - cron: "0 7 * * *"  # Run once daily

permissions:
  contents: read  # to fetch code (actions/checkout)

defaults:
  run:
    shell: bash -l {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  COMMIT_ID: ${{ github.sha }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_IAM_S3_UPLOADER }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_IAM_S3_UPLOADER }}

jobs:
  linux-wheel-builder:
    name: Build and test Python wheels (Linux amd64)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - uses: mamba-org/provision-with-micromamba@v14
      with:
        cache-downloads: true
        cache-env: true
        environment-name: dev
        environment-file: ops/conda_env/dev.yml
    - name: Display Conda env
      run: |
        conda info
        conda list
    - name: Build wheel
      run: |
        bash ops/build-linux.sh
    - name: Test wheel
      run: |
        bash ops/test-linux-python-wheel.sh
  linux-wheel-builder-aarch64:
    name: Build and test Python wheels (Linux aarch64)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - uses: mamba-org/provision-with-micromamba@v14
      with:
        cache-downloads: true
        cache-env: true
        environment-name: dev
        environment-file: ops/conda_env/dev.yml
    - name: Display Conda env
      run: |
        conda info
        conda list
    - name: Build wheel
      run: |
        bash ops/build-linux-aarch64.sh
  cpack-builder:
    name: Build CPack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - uses: mamba-org/provision-with-micromamba@v14
      with:
        cache-downloads: true
        cache-env: true
        environment-name: dev
        environment-file: ops/conda_env/dev.yml
    - name: Build CPack
      run: |
        bash ops/build-cpack.sh
