name: windows-wheel-builder

on: [push, pull_request]

permissions:
  contents: read  # to fetch code (actions/checkout)

defaults:
  run:
    shell: cmd /C CALL {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  COMMIT_ID: ${{ github.sha }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_IAM_S3_UPLOADER }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_IAM_S3_UPLOADER }}

jobs:
  windows-wheel-builder:
    name: Build and test Python wheels (Windows)
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - uses: mamba-org/provision-with-micromamba@v14
      with:
        cache-downloads: true
        cache-env: true
        environment-name: dev
        environment-file: ops/conda_env/dev.yml
    - name: Display Conda env
      run: |
        micromamba info
        micromamba list
    - name: Build wheel
      run: |
        call ops/build-windows.bat
    - name: Test wheel
      run: |
        call ops/test-win-python-wheel.bat
